import os
Import('common_env')
env = common_env.Clone()

Export('env')

cxx_sources = Glob('*.cxx')
c_sources = Glob('*.c')

objects = [ env.Object(s) for s in cxx_sources ] + [ env.Object(s) for s in c_sources ]

for subdir in [] :
        objects += SConscript( '%s/SConscript'%subdir )

Return('objects')

